### ISSUE TITLE
random crop resolution 320*448

### ISSUE THREAD

**Issue by poincarelee** [ClementPinard/FlowNetPytorch#112]
Hi, 
Thanks for your pioneering work and great contribution. 
I saw in your paper, you crop the image in flying-chairs to 512*384, while in main.py , the randomcrop was 320*448, Could you tell me why you chose this resolution?  
If I would like to use real scene dataset,  whose resolution is eg. 1920*1080,  how can I crop the image?

**Comment by ClementPinard** [comment]
Hello,

FlowNet is fully convolutive, you don't need a particular input resolution. As such, if your machine is beefy enough, you can feed the network fullHD images directly.

The reason we cropped the images to be 320x448 instead of full resolution is to be able to perform data augmentation such as random rotate, or translate one fo the image to create an artificial optical flow. If we stayed with full resolution, we would have ended up with many dead zones where no pixel is present, and thus no optical flow can be learned.

**Comment by poincarelee** [comment]
Thanks a lot for such a quick reply.  
Good explanation, I completely got it.

**Comment by poincarelee** [comment]
hmm, I have another question to ascertain, in  my real scene dataset(having images and groundtruth of flow), do I need to use co_transform?
