### ISSUE TITLE
Output of run_inference.py

### ISSUE THREAD

**Issue by xin-xinhanggao** [ClementPinard/FlowNetPytorch#34]
I use flownets_EPE1.951.pth.tar to test the examples below via run_inference.py

![t0](https://user-images.githubusercontent.com/20569510/38121192-57289860-3400-11e8-9377-c4d81f9ae5db.png)

![t1](https://user-images.githubusercontent.com/20569510/38121198-664d043e-3400-11e8-8959-b6db39698188.png)
And get result like this 

![_flow](https://user-images.githubusercontent.com/20569510/38121209-758866be-3400-11e8-9692-d0390f0dc81f.png)

The image size of the result is 128 * 96 just 1/16 of the original image. And it does not look like the ground truth in Readme.md. Is there some thing wrong?

**Comment by ClementPinard** [comment]
The output is supposed to be only H/4 x W/4. You can use any upscaling algorithm you want from there
to cite the original paper :
>We discover that further refinement from this resolution does not significantly improve the results, compared to a computationally less expensive bilinear upsampling to full image resolution. The result of this bilinear upsampling is the final flow predicted by he network.

I could have used a final upsampling pass, but prefered to let user choose. Maybe I could add it as an option.

As for color code, something is indeed off, but it's probably the flow2rgb that is off and not the network. I may have change it unintentionally since I generated the README flow maps, I'll take a look

**Comment by ClementPinard** [comment]
After some tests, You simply inverted input 0 and input 1 hence the inverted color map. Also to get exact same results as in README, you have to put `--max_flow` option to 10.

I also updated the scripts in order to let the user choose upsampling or not, and the possibility to output inverted flow (to avoid confusions like yours). Hope it solves your issue !

**Comment by 1292765944** [comment]
What does --max_flow = 10 mean here? So is there ground truth flow2rgb images?

**Comment by ClementPinard** [comment]
this option serves visualization purposes. Basically, the max color intensity is reached at optical flow of 10. That way, if your optical is very low, you can lower this threshold to amplify color intensities, otherwise you would get an almost white picture.

Similarly, if your optical flow is high, you can raise the threshold, otherwise it would get saturated fast you would'nt be able to see optical flow nuances above 10px.

We could normalize it so that the max_flow color intensity matches the max values of the optical flow map, but keeping this parameter manual ensures you have a good grasp of your optical flow absolute intensities.

**Comment by 1292765944** [comment]
Thank for you kind reply! By the way, I'm also confused about --div-flow option. It seems that we normalize the flow with std=div-flow and need to multiply the flownet ouput by 20 for the final flow in both training and testing. Is this really useful?

**Comment by ClementPinard** [comment]
the div-flow option was used in original caffe implementation.

They noted that the training was more stable if they divided the target optical flow by 20. As such, the network output needs to be multiplied by 20 if you want to get actual optical flow. The div-flow is just a way to put any manual factor you want (including 1), but it has to be consistent between training and inference.

**Comment by 1292765944** [comment]
Oh, maybe the motivation of --div-flow is the same as the --max_flow, and the normalized flow is easy for training in flying chair dataset. Thanks again for your help.
