### ISSUE TITLE
implementation channel of flow net is not match with your sample prediction and GT

### ISSUE THREAD

**Issue by Hamzeluie** [ClementPinard/FlowNetPytorch#60]
hi .i recently used your implementation of flownetS and i wanted to feed my own dataset to the net
which has 2 dimension [X, Y]. i convert this to 3 dimension with zero pad to feed to the net
after loading pretrained weights and applying my own data i see there is no any similarity between my predictions and my GTs
when i checked your sample (Inputs, GT, p) i saw your prediction and GT channel is 3 dimension which in our implementation has 2 channel

and also how do you read input gifs input which has (3, 384, 512, 4)?
i had problem when i wanted to split it to pic and save them to my dick

**Comment by ClementPinard** [comment]
Are you saying that your images are only grayscale and thus 2 dimensional ?
My advice would then be to replicate the gray chanel for every color chanel instead of padding it with 0.

```python
h, w = grayscale.size()
rgb = grayscale.expand(3, h, w)
```

As for the output, maybe you are talking about the RGB flow map, whose purpose is only visualization : the direct output of the network is of size `[2, h/4, w/4]`
To get the actual optical flow map, you need to upscale it to `[2, h, w]` and then multiply it by 20 (this factor is only a matter of convention).

Finally, you can convert gif to sequence of png images with imagemagick
https://www.imagemagick.org/discourse-server/viewtopic.php?t=22597

**Comment by Hamzeluie** [comment]
thank you so much 
it was so useful
