### ISSUE TITLE
flownet v1 or flownet v2

### ISSUE THREAD

**Issue by amiltonwong** [ClementPinard/FlowNetPytorch#7]
Hi, @ClementPinard ,

Which version does FlowNetPytorch match for?

[flownet v1](https://arxiv.org/abs/1504.06852) or [flownet v2](https://arxiv.org/abs/1612.01925)

**Comment by ClementPinard** [comment]
Hello, it's FlowNet v1.
Thanks to a recent [merge](https://github.com/pytorch/pytorch/pull/2007) , Pytorch now can use a Spatial Transformer Network, just as in FlowNet v2.

However, we still need a correlation layer to have a fully functional version of FlowNet v2 (or FlowNetC frome FlowNet v1).

It should not be too hard to implement a training workflow as in FlowNet v2, but with FlowNetS instead of FlowNetC in the first Pipeline. However, result will be significantly worse I believe.

**Comment by bkvie** [comment]
Can you elaborate on the Spatial Transformer Network? My understanding is that flownet 2 stacks several flownets. I am not sure they use a STN? Would be interesting to see though.

**Comment by ClementPinard** [comment]
flownet2 uses network concatenation.
The basic workflow is to compute flow with first network Then you can warp img2 to compensate this flow. That way, next network will only have to deal to very little values of flow since it will compute it from img1 and warped img2 (which would be the same as img1 if first flow computed was perfect)

The data you feed next network is then not raw output of the former, but modified input thanks to STN (which can propagate gradient)

**Comment by BostonLobster** [comment]
> flownet2 uses network concatenation.
> The basic workflow is to compute flow with first network Then you can warp img2 to compensate this flow. That way, next network will only have to deal to very little values of flow since it will compute it from img1 and warped img2 (which would be the same as img1 if first flow computed was perfect)
> 
> The data you feed next network is then not raw output of the former, but modified input thanks to STN (which can propagate gradient)

Hi @ClementPinard, I have a question about the order of the flow: if I input a image pair [img1, img2] into flownet(v1 or v2), it outputs a flow. Does this flow can be directly used to warp img2 to align with img1 or the inverse? 

I am confused by this question for a few days... Looking forward to your reply

**Comment by AIprogrammer** [comment]
> > flownet2 uses network concatenation.
> > The basic workflow is to compute flow with first network Then you can warp img2 to compensate this flow. That way, next network will only have to deal to very little values of flow since it will compute it from img1 and warped img2 (which would be the same as img1 if first flow computed was perfect)
> > The data you feed next network is then not raw output of the former, but modified input thanks to STN (which can propagate gradient)
> 
> Hi @ClementPinard, I have a question about the order of the flow: if I input a image pair [img1, img2] into flownet(v1 or v2), it outputs a flow. Does this flow can be directly used to warp img2 to align with img1 or the inverse?
> 
> I am confused by this question for a few days... Looking forward to your reply

Hi, have you solve the confusion? I noticed that the direct output of the network maybe 1/4 or 1/8 of the original input image size. I am a little confused how we could use the output to warp the image? By upsampling the output to the same size of the input?

**Comment by ClementPinard** [comment]
With STN, which performs an **inverse** warping, the optical flow can only be used to be compensated. Thus you can reconstruct img1 with pixels sampled from img2.
If you want to do the opposite you have several less easy solutions :
 - Compute inverse optical flow With flownet(img2, img1)
 - Invert Optical flow map analytically. This needs precautions as the optical flow is not always bijective (some pixels disappear behind other, the optical flow doesn't tell where the occluded went)
 - Compute img2 using **direct** warping. You will have ambiguous pixels though. The very recent [Kaolin](https://github.com/NVIDIAGameWorks/kaolin/#main-modules) project (look at the graphics section) might help you with several direct warping method, even if these methods are more suited for depth warping, in which ambiguity is not a problem since it is solved by the depth of the pixels (we know what pixels occludes the other because it's the closest)

**Comment by AIprogrammer** [comment]
> With STN, which performs an **inverse** warping, the optical flow can only be used to be compensated. Thus you can reconstruct img1 with pixels sampled from img2.
> If you want to do the opposite you have several less easy solutions :
> 
> * Compute inverse optical flow With flownet(img2, img1)
> * Invert Optical flow map analytically. This needs precautions as the optical flow is not always bijective (some pixels disappear behind other, the optical flow doesn't tell where the occluded went)
> * Compute img2 using **direct** warping. You will have ambiguous pixels though. The very recent [Kaolin](https://github.com/NVIDIAGameWorks/kaolin/#main-modules) project (look at the graphics section) might help you with several direct warping method, even if these methods are more suited for depth warping, in which ambiguity is not a problem since it is solved by the depth of the pixels (we know what pixels occludes the other because it's the closest)
> 
> As for for using a 1/4 optical flow size to warp a full resolution image, it's up to you what you chose. It's common to upscale the optical flow map the best differentiable way possible (ie bilinear or bicubic interpolation) so that your warped image still retains spatial information from higher resolution.

Thanks for your reply. What do you mean by 'optical flow can only be used to be compensated'?
As the project of https://github.com/NVIDIA/flownet2-pytorch directly output the flow which is the same size of image, so it works if we grid sample from the source image based on the output. And if we get the optical flow(img2, img1) through your code, can we directly upsample the flow to the size of image, and the use grid_sample(img1, flow) to predict the img2?

**Comment by ClementPinard** [comment]
The flownet2 architecture is a bit different and UpConvolution go until full size wherehas in flownet1 it stops at a quarter of the size.

And yes you can predict Img2 with flow(img2, img1) and grid_sample(img1, flow)
