### ISSUE TITLE
flownetc epe lower than original paper

### ISSUE THREAD

**Issue by jeffbaena** [ClementPinard/FlowNetPytorch#70]
Dear Clement,
thanks for your implementation. I have tested the network FlowNetC, with weights "flownetc_EPE1.766.tar" in sintel training clean (1041 frame pairs). The result is much better than the original:

yours EPE 2.26 px
original EPE 4.31 px
I would like to obtain the exact performance of FlowNetC.
Do you have the weights for that? Alternatively, do you have information (or a script) with the exact training schedule and data augmentation?

Congratulations on your great work!

Bests,
Stefano

**Comment by ClementPinard** [comment]
Hello, exact FlowNetC weights are available as a caffe network [here](https://lmb.informatik.uni-freiburg.de/resources/binaries/dispflownet/dispflownet-release-1.2.tar.gz)

@Kaixhin made the conversion for FlowNetS models, but the implementation for FlowNetC in pytorch (at least in this repository) is quite recent, and unfortunately no one found the time to convert it yet.

It's not my top priority for future projects, but I'd be happy to review a PR with the converted model !

**Comment by jeffbaena** [comment]
Thanks Clement for your prompt response, I would be happy to give it a try to convert the model.

Dear  @ClementPinard and @Kaixhin could you advice me a tool to convert weights from caffe network to pytorch, I saw there are some around, but they all seem either incomplete or not working properly.

Thanks,
Stefano

**Comment by ClementPinard** [comment]
it is not that easy because flownet models (S and C) have custom layers for data augmentation in them, causing regular caffe-pytorch translators (like e.g. https://github.com/marvis/pytorch-caffe ) to fail.

As far as I remember, I managed to transfer caffe weights to torch7 (back when pytorch was not out yet) with https://github.com/szagoruyko/loadcaffe and then I could transfer it from torch7 to pytorch.

I surely hope there's a more direct way now, but I did not make time to see what tools are available as of today.

Anything is acceptable as long as there is a .pth file in the end of the process that works reasonably well, and you are willing to help future users with potential problems with this pretrained version.

Thanks again for your help !

**Comment by jeffbaena** [comment]
Thanks to you! I see this is a cumbersome procedure, so maybe before I will try to train your implementation from scratch and see if we can get the same values as the original paper.

Regards,
Stefano

**Comment by jeffbaena** [comment]
Dear Clement,
 I am sorry, but the previous stated epe on sintel training clean is wrong (there was a bug in my evaluation code).

The correct values are reported below. This might be useful to other people using your models.


<table>
  <tr>
    <th>pass</th>
    <th>paper</th>
    <th><br>YOURS flownetc_EPE1.766.tar </th>
    <th>YOURS<br>retrained</th>
  </tr>
  <tr>
    <td>clean</td>
    <td>4,31</td>
    <td>4,70</td>
    <td>4,8</td>
  </tr>
  <tr>
    <td>final</td>
    <td>5,87</td>
    <td>6,21</td>
    <td>6,1</td>
  </tr>
</table>
