### ISSUE TITLE
Do we need divide the target_scaled by half when downsample (multiscaleloss.py)?

### ISSUE THREAD

**Issue by CXMANDTXW** [ClementPinard/FlowNetPytorch#77]
Thank you for your work on this.
I noticed in multiscaleloss.py ,you use F.upsample to downsample the target_flow to fit the output size.
But, when the size of the target flow drops by half, shall we to take half of the value of the target flow at the same time?

**Comment by ClementPinard** [comment]
Even the highest scale has an optical flow that  4times too big since it has been downsampled 4times.

As optical flow is computed from values only and not from geometrical deductions, you don't need it to be geometrically sensical everywhere. You could theoretically make the target optical flow to have a corresponding scale, while ensuring that the upscaling layers also multiply the flow by 2, but I doubt you'll get better results.

**Comment by CXMANDTXW** [comment]
Thanks a lot, I did an experiment and the results were not very good.
